resolver: lts-13.24

packages:
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- gi-gtk-declarative-components
- examples

extra-deps:
  - hedgehog-1.0

nix:
  packages: [pkgconfig, gnome3.gobjectIntrospection, gnome3.gtk]
