name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: dretch
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: 'Build and Test Libraries and Examples'
        run: nix-build -j2 --arg doCheck true
      - name: 'Build Docs'
        run: nix-shell -j2 --run 'cabal haddock all && cd docs && mkdocs build'
      - name: 'Publish Docs'
        if: github.ref == 'refs/heads/components'
        run: |
          git clone https://github.com/Dretch/dretch.github.io
          cd dretch.github.io
          mkdir -p gi-gtk-declarative/docs
          cp -r ../docs/site gi-gtk-declarative/docs/guide
          cp -r ../dist-newstyle/build/x86_64-linux/ghc-*/gi-gtk-declarative-0.*/doc/html/gi-gtk-declarative gi-gtk-declarative/docs/haddock
          git add --all
          git config user.name gi-gtk-declarative-ci
          git config user.email 'Dretch@users.noreply.github.com'
          git remote set-url origin https://Dretch:${{ secrets.PAGES_TOKEN }}@github.com/Dretch/dretch.github.io
          git commit -m 'Publish latest gi-gtk-declarative docs'
          git push origin
